# -*- coding: utf-8 -*-
"""classification_keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M3ISR5ZIQPSCM16dwMi2foiPo2KVWUUS
"""

import torch
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import cv2
import keras
import tensorflow as tf
from keras.utils import to_categorical
from keras.layers import Dense,Conv2D,Flatten,MaxPool2D,Dropout,GlobalAveragePooling2D, Input
from keras.models import Sequential
from keras.optimizers import schedules
import random
import shutil
from PIL import Image
from sklearn.model_selection import train_test_split

from google.colab import drive
drive.mount('/content/drive')

# Load model mask
model_mask = tf.keras.saving.load_model('/content/drive/MyDrive/model_mask.keras')
model_glass = tf.keras.saving.load_model('/content/model_glasses_2.keras')

img_path = '/content/drive/MyDrive/person_images.zip (Unzipped Files)/2023-05-31'

test_pic = '/content/s93-pa-4273.jpg' # ref : https://photodune.net/item/indian-man-volunteer-wearing-face-mask-in-the-new-normal-full-body/34833655

shape=(160,400)
im = cv2.imread(test_pic)
im = cv2.resize(im,shape)
#im = im.reshape(1,400,160,3)
imageRGB = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
imgg = Image.fromarray(imageRGB, 'RGB')
imgg

# Predict class
class_mask = sorted(["mask", "no_mask"])
class_glasses = sorted(["eye_glasses", "no_glasses", "sun_glasses"])
im = im.reshape(1,400,160,3) # reshape to fit model
label_pred = model_mask.predict(im)
pred_glass = model_glass.predict(im)
mask_pred_max = np.argmax(label_pred,axis=1)
glass_pred_max = np.argmax(pred_glass,axis=1)
print(mask_pred_max, class_mask[mask_pred_max[0]])
print(glass_pred_max, class_glasses[glass_pred_max[0]])